# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c5c7848f57b5c742f0b860b449059b4f27c7f0d1666aac854d070aa60a74e1b6f781f04d2e27ab2689912d0c8bb32ce686ffb0d94286c0f374e1bced1369f3c

test:
  secret_key_base: 863ea95216bd40479b15be065e5f8dba809fb57885d4a7093e1631166d61a28dae234093fee56f9a1d51ecb63a1c70b0341617d63a2700561c5827a35fd7d664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
